title: Muhammad Ali Farooq Homepage
page-top-title: Muhammad Ali Farooq
top-section-bg-text: 
home-subtitle: Muhammad Ali Farooq&ensp;|&ensp;محمد علي فاروق
copyright-text: '&copy; Muhammad Ali Farooq 2024-2025. All Rights Reserved.'
