title: Muhammad Ali Farooq Homepage
page-top-title: Muhammad Ali Farooq&ensp;|&ensp;محمد علي فاروق
top-section-bg-text:  ML Scientist | CV Researcher 
home-subtitle: About Me
copyright-text: '&copy; Muhammad Ali Farooq 2024-2025. All Rights Reserved.'
