title: Muhammad Ali Farooq Homepage
page-top-title: Muhammad Ali Farooq
top-section-bg-text: AI
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Muhammad Ali Farooq 2024-2025. All Rights Reserved.'
